apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kotro-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kotro-proxy.name" . }}
    helm.sh/chart: {{ include "kotro-proxy.chart" . }}
data:
  KOTRO_LISTEN_ADDR: ":8080"
  KOTRO_METRICS_ADDR: "0.0.0.0:9090"
  KOTRO_UPSTREAM_URL: {{ .Values.proxy.upstreamUrl | quote }}
  KOTRO_FALLBACK_URL: {{ .Values.proxy.fallbackUrl | quote }}
  KOTRO_ENABLE_CACHE: {{ .Values.proxy.enableCache | quote }}
  KOTRO_ENABLE_REDACTION: {{ .Values.proxy.enableRedaction | quote }}
  KOTRO_ENABLE_COMPRESSION: {{ .Values.proxy.enableCompression | quote }}
  KOTRO_CACHE_KEY_STRATEGY: {{ .Values.proxy.cacheKeyStrategy | quote }}
